### ISSUE TITLE
error: expected `std.io.Writer` interface value

### ISSUE THREAD

**Issue by Namek** [getty-zig/json#20]
### Description

I got the error 
```
error: expected `std.io.Writer` interface value, found `std.io.writer.Writer(std.fs.file.File,std.os.WriteError,std.fs.file.File.write)`
```
with the example from the README page for the `toWriter` function:

```zig
const std = @import("std");
const json = @import("json");

const Point = struct { x: i32, y: i32 };
const point = Point{ .x = 1, .y = 2 };

pub fn main() anyerror!void {
    const stdout = std.io.getStdOut().writer();

    // {"x":1,"y":2}
    try json.toWriter(point, stdout);
}
```

I get a similar error with `toSlice`
I guess this is about Zig version? Any workaround to stay on 0.9.1?

### How to Reproduce the Bug

Zig 0.9.1

### Additional Context

full error:
```
.\.gyro\json-getty-zig-github.com-9f451bd8\pkg\src\ser.zig:128:17: error: expected `std.io.Writer` interface value, found `std.io.writer.Writer(std.fs.file.File,std.os.WriteError,std.fs.file.File.write)`
                @compileError(err);
                ^
.\.gyro\json-getty-zig-github.com-9f451bd8\pkg\src\ser.zig:16:39: note: called from here
    comptime concepts.@"std.io.Writer"(@TypeOf(writer));
                                      ^
.\.gyro\json-getty-zig-github.com-9f451bd8\pkg\src\ser.zig:41:28: note: called from here
    return try toWriterWith(value, writer, getty.default_st);
                           ^
.\src\main.zig:11:22: note: called from here
    try json.toWriter(point, stdout);
                     ^
.\src\main.zig:7:29: note: called from here
pub fn main() anyerror!void {
```

**Comment by phan-do** [comment]
> I guess this is about Zig version?

Yeah. The type names for `std` types changed in stage2, which is why you're getting that error even though you're correctly passing in a `std.io.Writer`.

> Any workaround to stay on 0.9.1?

- If you're using Gyro, you can specify which version of Getty JSON to grab. In this case, I think 0172f55d90e16b50e2da4549578e632c87382352 is the latest version that would work. It uses a pre-stage2 version of Getty so everything should be fixed for you (probably... It maaaaay rely 0.10 stuff but I don't think that's the case).

  ```yaml
  # gyro.zzz

  ...

  deps:
    json:
      git:
        url: "https://github.com/getty-zig/json.git"
        ref: 0172f55d90e16b50e2da4549578e632c87382352
        root: src/lib.zig
  ```
- If you're using Zigmod, you can do the same thing. Although, now that I've looked, the `zigmod.yml` is way out-of-date and needs to be updated 😅 

  ```yaml
  # zigmod.yml

  ...

  dependencies:
    - src: git https://github.com/getty-zig/json
      version: commit-0172f55
  ```
- If you're building from source, then you can just grab the aforementioned commit and build that.

Hope that helps!
